language: c#

cache:
  - apt

install:
  - sudo apt-add-repository ppa:directhex/monoxide -y
  - sudo apt-get update
  - sudo apt-get -y -qq install mono-devel doxygen

script:
  - mozroots --import --sync
  - make all
