//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chicken4WP8.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chicken4WP8.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Enter PIN Code 的本地化字符串。
        /// </summary>
        public static string BaseOAuthSettingPageView_EnterPinCode {
            get {
                return ResourceManager.GetString("BaseOAuthSettingPageView_EnterPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorize with twitter 的本地化字符串。
        /// </summary>
        public static string BaseOAuthSettingPageView_Title {
            get {
                return ResourceManager.GetString("BaseOAuthSettingPageView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OAuth Setting 的本地化字符串。
        /// </summary>
        public static string OAuthSettingPageView_OAuthSettingTitle {
            get {
                return ResourceManager.GetString("OAuthSettingPageView_OAuthSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Authorization Type 的本地化字符串。
        /// </summary>
        public static string OAuthSettingPageView_OAuthTypesPickerHeader {
            get {
                return ResourceManager.GetString("OAuthSettingPageView_OAuthTypesPickerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        public static string ProgressBar_Loading {
            get {
                return ResourceManager.GetString("ProgressBar_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hello, {0}~ 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_HelloUser {
            get {
                return ResourceManager.GetString("Toast_Msg_HelloUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Twip Base URL 的本地化字符串。
        /// </summary>
        public static string TwipOAuthSettingPageView_Title {
            get {
                return ResourceManager.GetString("TwipOAuthSettingPageView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An Error Happened 的本地化字符串。
        /// </summary>
        public static string WaitCursor_AnErrorHappened {
            get {
                return ResourceManager.GetString("WaitCursor_AnErrorHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting Twitter Authorization Page... 的本地化字符串。
        /// </summary>
        public static string WaitCursor_GetAuthorizationPage {
            get {
                return ResourceManager.GetString("WaitCursor_GetAuthorizationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorizing... 的本地化字符串。
        /// </summary>
        public static string WaitCursor_GetCredentials {
            get {
                return ResourceManager.GetString("WaitCursor_GetCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting User Information... 的本地化字符串。
        /// </summary>
        public static string WaitCursor_GetCurrentUser {
            get {
                return ResourceManager.GetString("WaitCursor_GetCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        public static string WaitCursor_Loading {
            get {
                return ResourceManager.GetString("WaitCursor_Loading", resourceCulture);
            }
        }
    }
}
